# Code generated by font_to_py.py.
# Font: heart.ttf Char set: T
# Cmd: font_to_py.py heart.ttf 22 -c T heart.py
version = '0.42'

def height():
    return 21

def baseline():
    return 21

def max_width():
    return 29

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return False

def min_ch():
    return 84

def max_ch():
    return 84

_font =\
b'\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'\
b'\x00\x00\x00\x00\x00\x00\x00\x1d\x00\x07\xc0\x3c\x00\x0f\xf0\xff'\
b'\x00\x1f\xf9\xff\x80\x3f\xff\xff\xc0\x7f\xff\xff\xc0\x7f\xff\xff'\
b'\xc0\x7f\xff\xff\xc0\x7f\xff\xff\xe0\x7f\xff\xff\xc0\x7f\xff\xff'\
b'\xc0\x3f\xff\xff\xc0\x3f\xff\xff\x80\x1f\xff\xff\x00\x0f\xff\xff'\
b'\x00\x07\xff\xfe\x00\x03\xff\xfc\x00\x01\xff\xf8\x00\x00\xff\xe0'\
b'\x00\x00\x7f\xc0\x00\x00\x1f\x00\x00\x00\x06\x00\x00'

_index =\
b'\x00\x00\x17\x00\x6d\x00'

_mvfont = memoryview(_font)
_mvi = memoryview(_index)
ifb = lambda l : l[0] | (l[1] << 8)

def get_ch(ch):
    oc = ord(ch)
    ioff = 2 * (oc - 84 + 1) if oc >= 84 and oc <= 84 else 0
    doff = ifb(_mvi[ioff : ])
    width = ifb(_mvfont[doff : ])

    next_offs = doff + 2 + ((width - 1)//8 + 1) * 21
    return _mvfont[doff + 2:next_offs], 21, width


